name: C++ GCC CI with Makefile

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Analysis Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y cppcheck clang-tidy libgtest-dev cmake
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp lib/*.a /usr/lib

      - name: Run Cppcheck
        run: make cppcheck

      - name: Run Clang-Tidy
        run: make tidy

      - name: Environment and Execution Test
        run: make test

      - name: Install Build Wrapper
        run: |
          mkdir -p $HOME/.sonar
          curl -sSLo $HOME/.sonar/build-wrapper-linux-x86.zip https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip
          unzip -o $HOME/.sonar/build-wrapper-linux-x86.zip -d $HOME/.sonar
          echo "$HOME/.sonar/build-wrapper-linux-x86" >> $GITHUB_PATH

      - name: Run Build Wrapper and Test
        run: |
          make clean
          build-wrapper-linux-x86-64 --out-dir bw-output make test

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORG_KEY }}
            -Dsonar.sources=.
            -Dsonar.cfamily.build-wrapper-output=bw-output

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: pratice-binary
          path: my_app.exe